wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.23
    start_time: 1749754698.557952
    t:
      1:
      - 55
      3:
      - 13
      - 23
      4: 3.9.23
      5: 0.13.10
      8:
      - 5
